// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPVubwapNtgXIBAaalo9vnBwWY-3A7vD4',
    appId: '1:973935414908:web:c1771aab233b5adba8c3f9',
    messagingSenderId: '973935414908',
    projectId: 'capstone-5f898',
    authDomain: 'capstone-5f898.firebaseapp.com',
    databaseURL: 'https://capstone-5f898-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstone-5f898.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_13OUxgy7Zm2ruJsjNYYMe5kRSsrdnCw',
    appId: '1:973935414908:android:2608df94bd76af5ea8c3f9',
    messagingSenderId: '973935414908',
    projectId: 'capstone-5f898',
    databaseURL: 'https://capstone-5f898-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstone-5f898.appspot.com',
  );
}
